## Nb extentions

### Code

conda install -c conda-forge jupyter_contrib_nbextensions

### Link

https://github.com/ipython-contrib/jupyter_contrib_nbextensions

| Week Ending | State | House       | Carter | Grey  | Bailey   | Sloane | Cost Factor |
|-------------|-------|-------------|--------|-------|----------|--------|-------------|
| 1/1/18      | AL    | 265.0220523 | 298    | 58129 | 78976.57 | 39673  | 1.213153    |
| 1/8/18      | AL    | 421.5451436 | 474    | 59791 | 199812.4 | 94856  | 2.884635    |
| 1/15/18     | AL    | 450.0038875 | 506    | 62678 | 227702   | 100072 | 3.180266    |
| 1/22/18     | AL    | 314.8248541 | 354    | 60562 | 111448   | 44279  | 1.755642    |

In [6]:
import numpy as np

In [7]:
ex_1 = ['song', 'swing', 'big', 'building']

l = list()
for i in ex_1:
    l.append(len(i))

In [8]:
l

[4, 5, 3, 8]

In [16]:
rp = np.repeat(l, 4)
print(rp.reshape(2,8))

[[4 4 4 4 5 5 5 5]
 [3 3 3 3 8 8 8 8]]


In [20]:
rp.reshape(2,8).reshape(-1) ## Flatten it

array([4, 4, 4, 4, 5, 5, 5, 5, 3, 3, 3, 3, 8, 8, 8, 8])

In [19]:
print(np.tile(l, 4))

[4 5 3 8 4 5 3 8 4 5 3 8 4 5 3 8]


In [17]:
np.std(rp)

1.8708286933869707

In [18]:
ex_1 * 4

['song',
 'swing',
 'big',
 'building',
 'song',
 'swing',
 'big',
 'building',
 'song',
 'swing',
 'big',
 'building',
 'song',
 'swing',
 'big',
 'building']

In [21]:
[value if(2 < value < 8) else 'nope' for value in range(10)]

['nope', 'nope', 'nope', 3, 4, 5, 6, 7, 'nope', 'nope']